### ISSUE TITLE
Config option to allow this to work in multiplayer

### ISSUE THREAD

**Issue by Jole-C** [ButteryStancakes/SafeSoloScrap#1]
I don't know if this is standard behaviour and another mod stopped it from working, but if not it would be nice to have an option to allow this to work in multiplayer. I really like the idea of losing two handed scrap but keeping one handed.

**Comment by ButteryStancakes** [comment]
The v2.0.0 rewrite now includes a config setting to apply the reduced penalty to a game with up to 3 players!
